# Generated by Django 4.2.6 on 2023-11-02 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students_courses', '0001_initial'),
        ('courses', '0002_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='students', through='students_courses.StudentCourse', to=settings.AUTH_USER_MODEL),
        ),
    ]
